// v3/app/components/Header.tsx
"use client";

import { useEffect, useState } from "react";
import { FaBars, FaMoon, FaSun, FaTerminal } from "react-icons/fa";

const NAV_ITEMS = [
  { href: "#home", label: "Home" },
  { href: "#about-me", label: "Sobre mim" },
  { href: "#experience", label: "Experiência" },
  { href: "#academic-background", label: "Formação" },
  { href: "#projects", label: "Projetos" },
  { href: "#contact", label: "Contato" },
];

export function Header() {
  const [theme, setTheme] = useState<"light" | "dark">(() => getInitialTheme());
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const isDarkMode = theme === "dark";

  useEffect(() => {
    updateHtmlTheme(theme);
  }, [theme]);

  useEffect(() => {
    if (!isMenuOpen) return;
    const handler = () => setIsMenuOpen(false);
    window.addEventListener("resize", handler);
    return () => window.removeEventListener("resize", handler);
  }, [isMenuOpen]);

  useEffect(() => {
    if (typeof window === "undefined") return undefined;
    const media = window.matchMedia("(prefers-color-scheme: dark)");
    const handleChange = (event: MediaQueryListEvent) => {
      if (window.localStorage.getItem("theme")) return;
      const nextTheme = event.matches ? "dark" : "light";
      setTheme(nextTheme);
    };
    media.addEventListener("change", handleChange);
    return () => media.removeEventListener("change", handleChange);
  }, []);

  const toggleTheme = () => {
    const nextTheme = isDarkMode ? "light" : "dark";
    setTheme(nextTheme);
    if (typeof window !== "undefined") {
      window.localStorage.setItem("theme", nextTheme);
    }
  };

  return (
    <header className="fixed inset-x-0 top-0 z-50 border-b border-zinc-800 bg-zinc-900/90 text-white backdrop-blur">
      <div className="mx-auto flex h-20 max-w-screen-xl items-center px-4">
        <a
          href="https://mayra.dev"
          className="flex items-center"
          aria-label="Mayra Amaral"
          target="_blank"
          rel="noopener noreferrer"
        >
          <FaTerminal className="text-3xl" />
        </a>
        <nav className="ml-auto hidden items-center md:flex">
          <ul className="flex gap-6 text-sm font-medium">
            {NAV_ITEMS.map((item) => (
              <li key={item.href}>
                <a href={item.href} className="transition hover:text-blue-400">
                  {item.label}
                </a>
              </li>
            ))}
            <li>
              <a
                href="https://blog.mayra.dev"
                target="_blank"
                rel="noopener noreferrer"
                className="transition hover:text-blue-400"
              >
                Blog
              </a>
            </li>
          </ul>
        </nav>
        <div className="ml-6 flex items-center gap-3">
          <button
            onClick={toggleTheme}
            className="flex h-10 w-10 items-center justify-center rounded-full text-white transition hover:bg-white/10"
            aria-label={isDarkMode ? "Ativar tema claro" : "Ativar tema escuro"}
            type="button"
          >
            {theme === "dark" ? <FaSun className="text-2xl" /> : <FaMoon className="text-2xl" />}
          </button>
          <button
            onClick={() => setIsMenuOpen((value) => !value)}
            className="inline-flex h-10 w-10 items-center justify-center rounded-lg text-zinc-300 transition hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-blue-500 md:hidden"
            aria-controls="primary-navigation"
            aria-expanded={isMenuOpen}
            type="button"
          >
            <FaBars className="text-xl" />
          </button>
        </div>
      </div>
      {isMenuOpen ? (
        <nav id="primary-navigation" className="md:hidden">
          <ul className="flex flex-col gap-1 border-t border-zinc-800 bg-zinc-900 px-4 py-4 text-sm font-medium">
            {NAV_ITEMS.map((item) => (
              <li key={item.href}>
                <a
                  href={item.href}
                  onClick={() => setIsMenuOpen(false)}
                  className="block rounded px-3 py-2 transition hover:bg-white/10"
                >
                  {item.label}
                </a>
              </li>
            ))}
            <li>
              <a
                href="https://blog.mayra.dev"
                target="_blank"
                rel="noopener noreferrer"
                className="block rounded px-3 py-2 transition hover:bg-white/10"
              >
                Blog
              </a>
            </li>
          </ul>
        </nav>
      ) : null}
    </header>
  );
}

function getInitialTheme(): "light" | "dark" {
  if (typeof window === "undefined") {
    return "light";
  }
  const storedTheme = window.localStorage.getItem("theme");
  if (storedTheme) {
    return storedTheme === "dark" ? "dark" : "light";
  }
  return window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
}

function updateHtmlTheme(theme: "light" | "dark") {
  if (typeof window === "undefined") {
    return;
  }
  const html = document.documentElement;
  if (theme === "dark") {
    html.classList.remove("light");
    html.classList.add("dark");
  } else {
    html.classList.remove("dark");
    html.classList.add("light");
  }
}

// src/app/header/header.component.ts
import { Component, OnInit, HostListener } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrl: './header.component.css',
})
export class HeaderComponent implements OnInit {
  isDarkMode: boolean = false;

  ngOnInit(): void {
    const theme = localStorage.getItem('theme');
    if (theme) {
      this.isDarkMode = theme === 'dark';
      this.updateTheme();
    }
  }

  toggleTheme(): void {
    this.isDarkMode = !this.isDarkMode;
    localStorage.setItem('theme', this.isDarkMode ? 'dark' : 'light');
    this.updateTheme();
  }

  updateTheme(): void {
    const htmlElement = document.documentElement;
    if (this.isDarkMode) {
      htmlElement.classList.add('dark');
    } else {
      htmlElement.classList.remove('dark');
    }
  }
}

<nav class="bg-gray-900 text-white fixed w-full z-50">
  <div class="max-w-screen-xl h-20 px-10 flex flex-wrap items-center mx-auto p-5">
    <a href="https://mayra.dev" class="flex items-center">
      <span class="fa-solid fa-terminal text-3xl text-white"></span>
    </a>

    <div class="flex items-center gap-4 md:order-3 md:justify-end pl-12 ml-auto md:m-0">
      <div id="tooltip-default" role="tooltip"
        class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip dark:bg-gray-700">
        Mudar tema do site
        <div class="tooltip-arrow" data-popper-arrow></div>
      </div>

      <button data-collapse-toggle="navbar-default" type="button" id="menu-btn"
        class="inline-flex items-center p-3 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
        aria-controls="navbar-default" aria-expanded="false">
        <span class="sr-only">Abrir menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
            d="M1 1h15M1 7h15M1 13h15" />
        </svg>
      </button>

      <button (click)="toggleTheme()" class="text-white w-10" data-tooltip-target="tooltip-default">
        <span *ngIf="isDarkMode" class="fa-solid fa-sun text-2xl"></span>
        <span *ngIf="!isDarkMode" class="fa-solid fa-moon text-2xl"></span>
      </button>
    </div>

    <div class="hidden w-full md:block md:w-auto ml-auto" id="navbar-default">
      <ul
        class="font-medium flex flex-col p-4 md:p-0 mt-4 border rounded-lg md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 bg-gray-800 md:bg-gray-900 border-gray-700">
        <li>
          <a href="#home"
            class="block py-2 px-3 bg-blue-700 rounded md:bg-transparent md:p-0 text-white md:text-blue-500"
            aria-current="page">Home</a>
        </li>
        <li>
          <a href="#about-me"
            class="block py-2 px-3 rounded md:border-0 md:p-0 text-white md:hover:text-blue-500 hover:bg-gray-700 hover:text-white md:hover:bg-transparent">Sobre
            mim</a>
        </li>
        <li>
          <a href="#experience"
            class="block py-2 px-3 rounded md:border-0 md:p-0 text-white md:hover:text-blue-500 hover:bg-gray-700 hover:text-white md:hover:bg-transparent">Experiência</a>
        </li>
        <li>
          <a href="#academic-background"
            class="block py-2 px-3 rounded md:border-0 md:p-0 text-white md:hover:text-blue-500 hover:bg-gray-700 hover:text-white md:hover:bg-transparent">Formação</a>
        </li>
        <li>
          <a href="#projects"
            class="block py-2 px-3 rounded md:border-0 md:p-0 text-white md:hover:text-blue-500 hover:bg-gray-700 hover:text-white md:hover:bg-transparent">Projetos</a>
        </li>
        <li>
          <a href="#contact"
            class="block py-2 px-3 rounded md:border-0 md:p-0 text-white md:hover:text-blue-500 hover:bg-gray-700 hover:text-white md:hover:bg-transparent">Contato</a>
        </li>
        <li>
          <a href="#" target="_blank" rel="noopener noreferrer"
            class="block py-2 px-3 rounded md:border-0 md:p-0 text-white md:hover:text-blue-500 hover:bg-gray-700 hover:text-white md:hover:bg-transparent">Blog</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
